#!/bin/sh

if [ ! -d /tmp/CheckUser ]
 then
  mkdir /tmp/CheckUser
fi


Edward=Away
Megan=Away


macadresser=`wl -i eth1 assoclist`
antal=0
antal=`qcsapi_sockrpc get_count_assoc wifi0`

while [ $antal -gt 0 ]
do
  antal=`expr $antal - 1`
  macadresser="`qcsapi_sockrpc get_station_mac_addr wifi0 $antal`;$macadresser"
done

case "$macadresser" in
 *DC:0B:34:C0:D3:49*)
 Edward=Home
 ;;
esac

case "$macadresser" in
 *DC:BF:E9:A5:5F:EA*)
 Megan=Home
 ;;
esac

if [ "$Edward" = Home ]
then
 if [ ! -f /tmp/CheckUser/EdwardHome ]
 then
  touch /tmp/CheckUser/EdwardHome
  curl -X POST "http://192.168.2.3/apps/api/391/home?access_token=fa7a7129-0382-4f53-8085-bf659f9f5226"
 fi
else
 if [ -f /tmp/CheckUser/EdwardHome ]
 then
  rm -f /tmp/CheckUser/EdwardHome
  curl -X POST "http://192.168.2.3/apps/api/391/away?access_token=fa7a7129-0382-4f53-8085-bf659f9f5226"
  fi
fi

if [ "$Megan" = Home ]
then
 if [ ! -f /tmp/CheckUser/MeganHome ]
 then
  touch /tmp/CheckUser/MeganHome
  curl -X POST "http://192.168.2.3/apps/api/391/home?access_token=fa7a7129-0382-4f53-8085-bf659f9f5226"
 fi
else
 if [ -f /tmp/CheckUser/MeganHome ]
 then
  rm -f /tmp/CheckUser/MeganHome
  curl -X POST "http://192.168.2.3/apps/api/391/home?access_token=fa7a7129-0382-4f53-8085-bf659f9f5226"
 fi
fi

