#!/bin/sh

if [ ! -d /tmp/CheckUser ]
 then
  mkdir /tmp/CheckUser
fi


Edward=Away
Megan=Away


macadresser=`wl -i eth1 assoclist`
antal=0
antal=`qcsapi_sockrpc get_count_assoc wifi0`

while [ $antal -gt 0 ]
do
  antal=`expr $antal - 1`
  macadresser="`qcsapi_sockrpc get_station_mac_addr wifi0 $antal`;$macadresser"
done

case "$macadresser" in
 *DC:0B:34:C0:D3:49*)
 Edward=Home
 ;;
esac

case "$macadresser" in
 *DC:BF:E9:A5:5F:EA*)
 Megan=Home
 ;;
esac

if [ "$Edward" = Home ]
then
 if [ ! -f /tmp/CheckUser/EdwardHome ]
 then
  touch /tmp/CheckUser/EdwardHome
  curl "https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/installations/<AppID>/Phone/home?access_token=<Access Token>" -k
 fi
else
 if [ -f /tmp/CheckUser/EdwardHome ]
 then
  rm -f /tmp/CheckUser/EdwardHome
  curl "https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/installations/<AppID>/Phone/away?access_token=<Access Token>" -k
  fi
fi

if [ "$Megan" = Home ]
then
 if [ ! -f /tmp/CheckUser/MeganHome ]
 then
  touch /tmp/CheckUser/MeganHome
  curl "https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/installations/<AppID>/Phone/home?access_token=<Access Token>" -k
 fi
else
 if [ -f /tmp/CheckUser/MeganHome ]
 then
  rm -f /tmp/CheckUser/MeganHome
  curl "https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/installations/<AppID>/Phone/away?access_token=<Access Token>" -k
 fi
fi

